"""add leaderboard_opt_in and social indexes

Revision ID: 199d7e40f50e
Revises: 24b6d8772b7b
Create Date: 2026-08-24 12:17:22.151452

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199d7e40f50e'
down_revision: str | None = '24b6d8772b7b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('leaderboard_opt_in', sa.Boolean(), server_default='true', nullable=False))
    op.create_index('ix_user_progress_total_xp', 'user_progress', [sa.literal_column('total_xp DESC')], unique=False)
    op.create_index('ix_xp_events_feed', 'xp_events', [sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('awarded_xp > 0'))
    op.create_index('ix_xp_events_user_occurred_created', 'xp_events', ['user_id', sa.literal_column('occurred_on DESC'), sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xp_events_user_occurred_created', table_name='xp_events')
    op.drop_index('ix_xp_events_feed', table_name='xp_events', postgresql_where=sa.text('awarded_xp > 0'))
    op.drop_index('ix_user_progress_total_xp', table_name='user_progress')
    op.drop_column('user_preferences', 'leaderboard_opt_in')
    # ### end Alembic commands ###
