"""add reminders, push_subscriptions, notifications

Revision ID: 24b6d8772b7b
Revises: b2c3d4e5f6a7
Create Date: 2026-08-21 10:53:14.868768

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b6d8772b7b'
down_revision: str | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('reminder', 'achievement', 'level_up', 'streak_risk', 'system', name='notification_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_id_desc', 'notifications', ['user_id', sa.literal_column('id DESC')], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    # Alembic does NOT auto-create an ENUM nested inside `postgresql.ARRAY` —
    # `CREATE TABLE` below would fail with `type "reminder_channel" does not
    # exist` without this explicit `.create()` first (D7-2 in
    # PHASE_7_8_9_PLAN.md). The column itself is then typed with
    # `create_type=False` so `create_table` doesn't try to create it again.
    reminder_channel_enum = postgresql.ENUM('push', 'in_app', name='reminder_channel')
    reminder_channel_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('habit_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('remind_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('rrule', sa.String(length=255), nullable=True),
    sa.Column('channels', postgresql.ARRAY(postgresql.ENUM('push', 'in_app', name='reminder_channel', create_type=False)), server_default=sa.text("'{push,in_app}'::reminder_channel[]"), nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'sent', 'dismissed', 'cancelled', name='reminder_status'), server_default='scheduled', nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT (task_id IS NOT NULL AND habit_id IS NOT NULL)', name='ck_reminders_single_target'),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_due', 'reminders', ['remind_at'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index(op.f('ix_reminders_habit_id'), 'reminders', ['habit_id'], unique=False)
    op.create_index(op.f('ix_reminders_task_id'), 'reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_index('ix_reminders_user_remind_at', 'reminders', ['user_id', 'remind_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reminders_user_remind_at', table_name='reminders')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_task_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_habit_id'), table_name='reminders')
    op.drop_index('ix_reminders_due', table_name='reminders', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_table('reminders')
    postgresql.ENUM('push', 'in_app', name='reminder_channel').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_notifications_user_id_desc', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_table('notifications')
    # ### end Alembic commands ###
