"""add focus_sessions and user_preferences

Revision ID: 4d5b624dd0d1
Revises: 30ba64afb48e
Create Date: 2026-08-18 10:26:46.546788

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d5b624dd0d1'
down_revision: str | None = '30ba64afb48e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('focus_minutes', sa.Integer(), server_default='25', nullable=False),
    sa.Column('short_break_minutes', sa.Integer(), server_default='5', nullable=False),
    sa.Column('long_break_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('sessions_before_long_break', sa.Integer(), server_default='4', nullable=False),
    sa.Column('sound_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('focus_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('focus', 'short_break', 'long_break', name='focus_mode'), nullable=False),
    sa.Column('planned_seconds', sa.Integer(), nullable=False),
    sa.Column('actual_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'completed', 'abandoned', name='focus_status'), server_default='running', nullable=False),
    sa.Column('xp_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_sessions_task_id'), 'focus_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.create_index('ix_focus_sessions_user_started', 'focus_sessions', ['user_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_focus_sessions_user_started', table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_task_id'), table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
