"""add skilltree and achievement tables

Revision ID: f11cc752ae9a
Revises: 5a3a9cdc8aae
Create Date: 2026-08-20 09:11:56.473533

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11cc752ae9a'
down_revision: str | None = '5a3a9cdc8aae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tier', sa.Enum('bronze', 'silver', 'gold', 'legendary', name='achievement_tier'), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_table('skill_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    # `skill_branch` already exists (phase-2 projects migration) — reused here,
    # same create_type=False hazard as xp_events.skill_branch (§6.1).
    sa.Column(
        'branch',
        postgresql.ENUM(
            'focus', 'health', 'discipline', 'growth', 'wealth',
            name='skill_branch', create_type=False,
        ),
        nullable=True,
    ),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('xp_cost', sa.Integer(), nullable=False),
    sa.Column('prerequisite_codes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('layout_x', sa.Integer(), nullable=False),
    sa.Column('layout_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_nodes_code'), 'skill_nodes', ['code'], unique=True)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    op.create_table('user_skill_nodes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['skill_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_skill_nodes')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_skill_nodes_code'), table_name='skill_nodes')
    op.drop_table('skill_nodes')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
